#!/bin/bash

# Copyright (c) 2019, AT&T Intellectual Property.  All rights reserved.
#
# SPDX-License-Identifier: GPL-2.0-only

if dmidecode | grep -qw 'T77O994T01_R02' || \
   dmidecode | grep -qw 'S9500-30XS'; then
	python3 /usr/lib/python3/dist-packages/platform_utility.py init
fi

